# 公共配置地址  -m standalone
base:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: BVxVx5hS
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
  rabbit:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
logging:
  level:
    com.alibaba.nacos: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS

server:
  tomcat:
    max-threads: 200 # Maximum amount of worker threads.
    min-spare-threads: 10 # Minimum amount of worker threads

spring:
  http:
    multipart:
      max-file-size: 100Mb      # Max file size，默认1M
      max-request-size: 100Mb   # Max request size，默认10M
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9006

hystrix: 
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

# ribbon配置
ribbon:
  # ribbon请求连接的超时时间 默认2秒 ms
  ConnectTimeout: 120000
  # 请求处理的超时时间 默认5秒 ms
  ReadTimeout: 120000
  # 对所有操作请求都进行重试,不配置这个MaxAutoRetries不起作用 默认false
  OkToRetryOnAllOperations: true
  # 对当前实例的重试次数 默认0
  MaxAutoRetries: 1
  # 切换实例的重试次数 默认1
  MaxAutoRetriesNextServer: 2
  # 自定义的ribbon负载均衡策略 默认com.netflix.loadbalancer.AvailabilityFilteringRule
  # NFLoadBalancerRuleClassName: cn.taroco.common.ribbon.XlabelWeightMetadataRule
  # 从注册中心刷新servelist的时间 默认30秒 ms
  ServerListRefreshInterval: 15000

feign:
  sentinel:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true