# jpa配置 数据源配置
spring:
  http:
    multipart:
      max-file-size: 100Mb      # Max file size，默认1M
      max-request-size: 100Mb   # Max request size，默认10M
  datasource:
    url: ${base.mysql.url}/ql_coin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ${base.mysql.username}
    password: ${base.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: XA87-member-HikariCP
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0
  rabbitmq:
    host: ${base.rabbit.host}
    port: ${base.rabbit.port}
    username: ${base.rabbit.username}
    password: ${base.rabbit.password}
    publisher-confirms: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.xa87.o2o.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.alibaba.nacos: warn
    cn.xa87.data.mapper: debug
xa87:
  # swagger2配置
  swagger:
    enabled: true
    title: Xa87-data
    description: Xa87-member RestFull Api
    version: 1.0.0
    license: 
    license-url: 
    terms-of-service-url: 
    contact:
      name: yuzhen
      url: https://xa87.cn/
      email: 353145552@qq.com
    base-package: cn.xa87.data.controller
    base-path: /**
    exclude-path: /error
