# jpa配置 数据源配置
spring:
  datasource:
    url: ${base.mysql.url}/ql_coin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: ${base.mysql.username}
    password: ${base.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: XA87-JOB-HikariCP
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0
  rabbitmq:
    host: ${base.rabbit.host}
    port: ${base.rabbit.port}
    username: ${base.rabbit.username}
    password: ${base.rabbit.password}
    publisher-confirms: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.xa87.o2o.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:1090/xxl-job-admin
    executor:
        appname: xa87-job-service
        address: 
        ip: 
        port: 8077
        logpath: /data/ql-project/xa87-job-service/logs
        logretentiondays: 1
    accessToken: