# 服务网关配置
spring:
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0
  security:
    basic:
      enabled: true
      path: /swagger-ui.html
    user:
      name: admin
      password: admin
# 路由配置
zuul:
  retryable: true
  #　忽略所有默认路由
  ignored-services: '*'
  # 需要聚合的swagger服务
  swagger:
    serviceIds: xa87-data-service,xa87-member-service,xa87-contract-service,xa87-entrust-service,xa87-otc-service
  FormBodyWrapperFilter: 
    pre:
      disable: false
